### ISSUE TITLE
AnyType support

### ISSUE THREAD

**Issue by Gama11** [cjbooms/fabrikt#106]
openapi-generator and swagger-codegen support "any" types via typeless schemas:

https://swagger.io/docs/specification/data-models/data-types/#any

It seems right now fabrikt doesn't support this:

```yml
openapi: 3.0.0
components:
  schemas:
    Foo:
      type: object
      properties:
        bar:
          $ref: '#/components/schemas/AnyValue'
    AnyValue:
      description: Can be any value - string, number, boolean, array or object.
```

```
Exception in thread "main" com.beust.jcommander.ParameterException: Invalid models or api file:
ValidationError(reason=Property 'bar' cannot be parsed to a Schema. Check your input)
        at com.cjbooms.fabrikt.model.SourceApi.<init>(SourceApi.kt:37)
        at com.cjbooms.fabrikt.model.SourceApi$Companion.create(SourceApi.kt:28)
        at com.cjbooms.fabrikt.cli.CodeGen.generate(CodeGen.kt:50)
        at com.cjbooms.fabrikt.cli.CodeGen.main(CodeGen.kt:22)
```

By default openapi-generator uses `kotlin.Any`: https://github.com/OpenAPITools/openapi-generator/pull/10070

In our project we map `AnyType` to Jackson's `JsonNode` since that seemed a bit more convenient to work with.

**Comment by cjbooms** [comment]
It's the first time I have encountered `AnyValue`. But it should be trivial enough to support as an `Any`.

**Comment by cjbooms** [comment]
I'm more comfortable using Any than a Jackson type. Let me know what you think. If you're happy I'll cut a new release

**Comment by Gama11** [comment]
Jackson should be fine with either, and I can definitely see the argument in favor of `Any`, for instance in case support for other JSON libraries is added.

I did find this when briefly searching for `JsonNode` in the sources, which suggests that it's already being used as a sort of Any type in one case at least? Not sure if it's important to be consistent here.

https://github.com/cjbooms/fabrikt/blob/e4a66d686be91e1d943c3f788ba9c86fba249dfa/src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt#L23

**Comment by cjbooms** [comment]
I interpreted the spec incorrectly and unfortunately it'll be a bit more complicated to get this working that I first imagined. 

I'll try and have another pop at it this evening or tomorrow.

**Comment by Gama11** [comment]
No worries. :)

Btw,  openapi-generator also considers `foo` to be of type "any"  in the following example using `oneOf` (which seems somewhat similar to the "serveral possible response schemas" case mentioned in that comment I linked):

```yml
openapi: 3.0.0
components:
  schemas:
    Foo:
      type: object
      properties:
        foo:
          oneOf:
            - type: string
            - type: object
              properties:
                a:
                  type: string
                b:
                  type: string

```

It looks like right now fabrikt just uses the first schema here:

```kotlin
data class Foo(
  @param:JsonProperty("foo")
  @get:JsonProperty("foo")
  val foo: String? = null
)
```

**Comment by Gama11** [comment]
Looks good, thanks! :)
