### ISSUE TITLE
Add support for arbitrary `oneOf` types

### ISSUE THREAD

**Issue by atollk** [cjbooms/fabrikt#141]
Currently, Fabrikt only supports the use of `oneOf` on `object` types. By OAS 3.0, it is allowed to use pretty much any type as well, like so:
```yaml
oneOf:
  - type: integer
```

At the moment, this causes an error:
```
Exception in thread "main" java.lang.IllegalStateException: Unknown OAS type: integer and format: null and specialization: ONE_OF_ANY
	at com.cjbooms.fabrikt.model.OasType$Companion.toOasType(OasType.kt:62)
	at com.cjbooms.fabrikt.model.KotlinTypeInfo$Companion.from(KotlinTypeInfo.kt:55)
	at com.cjbooms.fabrikt.model.PropertyInfo$Field.<init>(PropertyInfo.kt:155)
	at com.cjbooms.fabrikt.model.PropertyInfo$Companion.getInLinedProperties(PropertyInfo.kt:114)
	at com.cjbooms.fabrikt.model.PropertyInfo$Companion.topLevelProperties(PropertyInfo.kt:54)
	at com.cjbooms.fabrikt.generators.model.JacksonModelGenerator.createModels(JacksonModelGenerator.kt:152)
	at com.cjbooms.fabrikt.generators.model.JacksonModelGenerator.generate(JacksonModelGenerator.kt:134)
	at com.cjbooms.fabrikt.cli.CodeGenerator.models(CodeGenerator.kt:58)
	at com.cjbooms.fabrikt.cli.CodeGenerator.generateControllerInterfaces(CodeGenerator.kt:44)
	at com.cjbooms.fabrikt.cli.CodeGenerator.generateCode(CodeGenerator.kt:36)
	at com.cjbooms.fabrikt.cli.CodeGenerator.generate(CodeGenerator.kt:31)
	at com.cjbooms.fabrikt.cli.CodeGen.generate(CodeGen.kt:58)
	at com.cjbooms.fabrikt.cli.CodeGen.main(CodeGen.kt:22)
```

**Comment by cjbooms** [comment]
@atollk thanks for reporting this. I've just released `6.1.0` with the fix. It'd be great if you could confirm the fix and either close this issue or report back
