### ISSUE TITLE
Error when combining allOf with oneOf

### ISSUE THREAD

**Issue by Ehsan-khaveh** [cjbooms/fabrikt#238]
I have a valid 3.0 spec as such:

```
Vehicle:
  allOf:
    - type: object
      properties:
        id:
          type: string
          nullable: false
        brandName:
          type: string
          nullable: false
      required:
        - id
        - brandName
    - oneOf:
        - $ref: '#/components/schemas/Bus'
        - $ref: '#/components/schemas/Car'
      discriminator:
        propertyName: vehicleType
```

When I try to generate the client with this I get

```
Exception in thread "main" java.lang.NullPointerException: it.name must not be null
        at com.cjbooms.fabrikt.generators.model.JacksonModelGenerator.buildPrimaryModel(JacksonModelGenerator.kt:227)
        at com.cjbooms.fabrikt.generators.model.JacksonModelGenerator.createModels(JacksonModelGenerator.kt:168)
        at com.cjbooms.fabrikt.generators.model.JacksonModelGenerator.generate(JacksonModelGenerator.kt:148)
        at com.cjbooms.fabrikt.cli.CodeGenerator.models(CodeGenerator.kt:66)
        at com.cjbooms.fabrikt.cli.CodeGenerator.generateClient(CodeGenerator.kt:56)
        at com.cjbooms.fabrikt.cli.CodeGenerator.generateCode(CodeGenerator.kt:37)
        at com.cjbooms.fabrikt.cli.CodeGenerator.generate(CodeGenerator.kt:33)
        at com.cjbooms.fabrikt.cli.CodeGen.generate(CodeGen.kt:66)
        at com.cjbooms.fabrikt.cli.CodeGen.main(CodeGen.kt:22)
```

Is this a known issue/limitation with the lib? Or am I doing something wrong here?

**Comment by cjbooms** [comment]
Yes, I would say this is a limitation, I have never seen a modelling like this and wouldn't know what fabrikt should generate for it.

I would guess you can remodel your schema to something more interpretable, while maintaining the same contract.

**Comment by oleksii-dubinin** [comment]
> Thanks for the reply. What I want to achieve is to have some properties that are included in both types without having to repeat those in the schema of each. In the example above instances of `Car` and `Bus` would both have an `id` and a `brand`. I guess there is no way around it if the generator doesn't support that. Those properties would have to be repeated for every type.

If I understand you correctly, it should be possible.
You can put common attribute in a dedicated object and then ref to it from Car and Bus.

Smth like (sorry for formatting):
````yaml
CommonAttributes:
      type: object
      properties:
          id:
              type: string
          name:
              type: string
              
Car:
      allOf:
        - $ref: '#/components/schemas/CommonAttributes'
        - type: object
          required:
            - carAttribute1
            - carAttribute2
            
Bus:
    allOf:
        - $ref: '#/components/schemas/CommonAttributes'
        - type: object
          required:
            - busAttribute1
````

**Comment by Ehsan-khaveh** [comment]
Thanks for the suggestion. 

That does the trick but I was hoping I didn't have to change the spec, which is a valid OpenApi 3.0 spec, due to a limitation of the library. But I guess there is no way around it.
