### ISSUE TITLE
Generator doesnt work on YAML or JSON files larger than 3MB

### ISSUE THREAD

**Issue by nd-jharn** [cjbooms/fabrikt#271]
SnakeYaml added a codepointlimit of 3145728 by default preventing you from generating any yaml spec larger than 3 megabytes.

For example, the [Github OpenAPI](https://github.com/github/rest-api-description/blob/main/descriptions/ghes-3.9/ghes-3.9.yaml) can no longer be generated using FabriKT:

```bash
java -jar build/libs/fabrikt-13.0.1.jar \                                                 
             --output-directory './gen-sample' \
             --base-package 'com.example' \
             --api-file './ghes-3.9-openapi3.1.yaml' \
             --targets 'client' \
             --targets 'http_models' \
             --http-client-opts resilience4j
```

output:
```
Apr 11, 2024 1:41:45 PM com.cjbooms.fabrikt.cli.CodeGen generate
INFO: Generating code and dumping to ./gen-sample/
Exception in thread "main" com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: The incoming YAML document exceeds the limit: 3145728 code points.
 at [Source: (StringReader); line: 85148, column: 62]
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:435)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:1091)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:539)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:100)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4867)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3219)
	at com.cjbooms.fabrikt.util.YamlUtils.parseOpenApi(YamlUtils.kt:41)
	at com.cjbooms.fabrikt.model.SourceApi.<init>(SourceApi.kt:35)
	at com.cjbooms.fabrikt.model.SourceApi$Companion.create(SourceApi.kt:31)
	at com.cjbooms.fabrikt.cli.CodeGen.generate(CodeGen.kt:66)
	at com.cjbooms.fabrikt.cli.CodeGen.main(CodeGen.kt:22)
Caused by: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:317)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:639)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:172)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:429)
	... 12 more
```

**Comment by cjbooms** [comment]
> can no longer be generated

Did it work at a previous point in time?

Also, do you know if this limit configurable via code?

**Comment by cjbooms** [comment]
Looks like this is the fix:
https://stackoverflow.com/a/74805442/1026785
