### ISSUE TITLE
Parameter `--external-ref-resolution` seems to be failing

### ISSUE THREAD

**Issue by Aschraf** [cjbooms/fabrikt#332]
Hello,
I'm trying to generate models from a multi-file api and was experimenting with `--external-ref-resolution` but it gives:

```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--external-ref-resolution' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:961)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:762)
        at com.beust.jcommander.JCommander.parse(JCommander.java:363)
        at com.beust.jcommander.JCommander.parse(JCommander.java:342)
        at com.cjbooms.fabrikt.cli.CodeGenArgs$Companion.parse(CodeGenArgs.kt:29)
        at com.cjbooms.fabrikt.cli.CodeGen.main(CodeGen.kt:17)
```
for info, here are all my args:

```       
 args = listOf(
            "--output-directory", generationDir,
            "--base-package", "com.example",
            "--api-file", apiFile,
            "--targets", "http_models",
            "--http-model-opts", "SEALED_INTERFACES_FOR_ONE_OF",
            "--validation-library", "JAKARTA_VALIDATION",
            "--external-ref-resolution", "TARGETED"
        )
```

Is this parameter actually supported?
Thanks

**Comment by cjbooms** [comment]
Seems to work as expected
https://github.com/cjbooms/fabrikt/pull/333
https://github.com/cjbooms/fabrikt/actions/runs/11951031296/job/33313792959
