### ISSUE TITLE
Fabrikt misleadingly reports "Failed to resolve references when parsing API...", masking the actual exception

### ISSUE THREAD

**Issue by gregopet** [cjbooms/fabrikt#92]
I have an OpenAPI specification that cannot be parsed for some reason. When fabrikt tries to convert it I get an error with the message `Failed to resolve references when parsing API. External Schema references require internet connection` even though the specification contains no external references. My first hunch was that it is actually a relative path problem, but catching the exception that triggers this message (in `YamlUtils.kt:41`) I am inclined to think the root `NullPointerException` has nothing to do with the message and is actually a bug in the underlying library. That same specification can certainly be parsed with openapi-generator or SwaggerUI.

I can try to replicate the example as I cannot (yet) share the actual OpenAPI specification but the stacktrace of the triggering exception looks like this: 

```
java.lang.NullPointerException
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.getAllowedJsonTypes(ValidatorBase.java:419)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateField(ValidatorBase.java:222)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateBooleanField(ValidatorBase.java:71)
	at com.reprezen.kaizen.oasparser.val3.EncodingPropertyValidator.runObjectValidations(EncodingPropertyValidator.java:38)
	at com.reprezen.kaizen.oasparser.val.ObjectValidatorBase.runValidations(ObjectValidatorBase.java:18)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.MapValidator.runValidations(MapValidator.java:31)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMap(ValidatorBase.java:285)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMapField(ValidatorBase.java:279)
	at com.reprezen.kaizen.oasparser.val3.MediaTypeValidator.runObjectValidations(MediaTypeValidator.java:38)
	at com.reprezen.kaizen.oasparser.val.ObjectValidatorBase.runValidations(ObjectValidatorBase.java:18)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.MapValidator.runValidations(MapValidator.java:31)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMap(ValidatorBase.java:285)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMapField(ValidatorBase.java:279)
	at com.reprezen.kaizen.oasparser.val3.RequestBodyValidator.runObjectValidations(RequestBodyValidator.java:28)
	at com.reprezen.kaizen.oasparser.val.ObjectValidatorBase.runValidations(ObjectValidatorBase.java:18)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateField(ValidatorBase.java:225)
	at com.reprezen.kaizen.oasparser.val3.OperationValidator.runObjectValidations(OperationValidator.java:48)
	at com.reprezen.kaizen.oasparser.val.ObjectValidatorBase.runValidations(ObjectValidatorBase.java:18)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.MapValidator.runValidations(MapValidator.java:31)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMap(ValidatorBase.java:285)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMapField(ValidatorBase.java:279)
	at com.reprezen.kaizen.oasparser.val3.PathValidator.runObjectValidations(PathValidator.java:32)
	at com.reprezen.kaizen.oasparser.val.ObjectValidatorBase.runValidations(ObjectValidatorBase.java:18)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.MapValidator.runValidations(MapValidator.java:31)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMap(ValidatorBase.java:285)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMapField(ValidatorBase.java:279)
	at com.reprezen.kaizen.oasparser.val3.OpenApi3Validator.runObjectValidations(OpenApi3Validator.java:56)
	at com.reprezen.kaizen.oasparser.val.ObjectValidatorBase.runValidations(ObjectValidatorBase.java:18)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:65)
	at com.reprezen.kaizen.oasparser.ovl3.OpenApi3Impl.validate(OpenApi3Impl.java:60)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:96)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:85)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:35)
	at com.reprezen.kaizen.oasparser.OpenApi3Parser.parse(OpenApi3Parser.java:29)
	at com.reprezen.kaizen.oasparser.OpenApi3Parser.parse(OpenApi3Parser.java:20)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:28)
	at com.reprezen.kaizen.oasparser.OpenApi3Parser.parse(OpenApi3Parser.java:24)
	at com.cjbooms.fabrikt.util.YamlUtils.parseOpenApi(YamlUtils.kt:39)
	at com.cjbooms.fabrikt.model.SourceApi.<init>(SourceApi.kt:32)
	at com.cjbooms.fabrikt.model.SourceApi$Companion.create(SourceApi.kt:28)
	at com.cjbooms.fabrikt.cli.CodeGen.generate(CodeGen.kt:50)
	at com.cjbooms.fabrikt.cli.CodeGen.main(CodeGen.kt:22)
```

**Comment by gregopet** [comment]
I can confirm it's an issue in the underlying lib. Incrementing the version of `com.reprezen.kaizen:openapi-parser` to `4.0.4` fabrikt can now process the specification successfuly.

**Comment by cjbooms** [comment]
As you might have guessed, this particular error message was added as a failures like this were almost always due to the spec having an unresolvable reference. 

Thanks for the report and investigation. I'll bump the library and improve this error message. 

Do you have a minimal spec that triggers it so I can add a test?

**Comment by gregopet** [comment]
Not right now, but I can probably come up with something in the evening (or else one of these days, my schedules are `var` not `val` :P )

**Comment by gregopet** [comment]
As as said, my time is a `var` :laughing: 

I found some unexpected time, here is a minimal spec that fails. The `encoding` seems to trigger it:

```
openapi: 3.0.1
info:
  title: Sample API
  version: "1.0"
paths:
  /endpoint:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
            encoding:
              image:
                contentType: image/png, image/jpeg, image/webp
      responses:
        200:
          description: Everything OK
```

**Comment by cjbooms** [comment]
Nice one. I validated that failure mode in a unit test
